server:
  port: 9088

spring:
  datasource:
    url: jdbc:mysql://gigamysql.mysql.database.azure.com:3306/crud
    username: admin1
    password: Password@123
  jpa:
    hibernate:
      ddl-auto: update

